### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by aleksei-timofeyev** [CroatiaControlLtd/asterix#42] opened 2016-06-21 12:03 UTC
**Run asterix:**
./asterix -jh -i 232.1.1.12:10.10.3.103:21112

**Send data to it:**
echo -ne "\xf0\x00\x04\x80\x01\x01" | socat - udp-datagram:232.1.1.12:21112,ip-add-membership=232.1.1.12:10.10.3.103

**Debug messages:**
`DEBUG:   Jun 21 16:51:59 2016 (asterix.cpp) Input channel description: udp 232.1.1.12:10.10.3.103:21112 ASTERIX_RAW

DEBUG:   Jun 21 16:51:59 2016 (asterix.cpp) Output channel 1 description: std 0 ASTERIX_JSONH

DEBUG:   Jun 21 16:51:59 2016 (converterengine.cxx) inputDevice(udp)
DEBUG:   Jun 21 16:51:59 2016 (converterengine.cxx) inputDeviceDescriptor(232.1.1.12:10.10.3.103:21112)
DEBUG:   Jun 21 16:51:59 2016 (converterengine.cxx) inputFormatDescriptor((null))
DEBUG:   Jun 21 16:51:59 2016 (converterengine.cxx) Input format: ASTERIX_RAW

DEBUG:   Jun 21 16:51:59 2016 (channelfactory.cxx) CChannelFactory successfully initialized with CAsterixFormat.

DEBUG:   Jun 21 16:51:59 2016 (udpdevice.cxx) Successfully joined multicast 232.1.1.12

DEBUG:   Jun 21 16:51:59 2016 (channelfactory.cxx) AttachFormatter ASTERIX_RAW

DEBUG:   Jun 21 16:51:59 2016 (converterengine.cxx) Output format: ASTERIX_JSONH

DEBUG:   Jun 21 16:51:59 2016 (channelfactory.cxx) AttachFormatter ASTERIX_JSONH

DEBUG:   Jun 21 16:52:03 2016 (udpdevice.cxx) Read message from 10.10.3.103 on address 10.10.3.103.
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) InputParser::parsePacket m_pBuffer=0x2767500 bufferSize=6
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataBlock::DataBlock len=1, data=0x2767503
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=1 data=0x2767503
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) UAP not found for category 240
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) Wrong Asterix data length (256)
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataBlock::DataBlock len=65535, data=0x2767507
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65535 data=0x2767507
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65534 data=0x2767508
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65521 data=0x2767515
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65520 data=0x2767516
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65519 data=0x2767517
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65518 data=0x2767518
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65508 data=0x2767522
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65485 data=0x2767539
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65476 data=0x2767542
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65456 data=0x2767556
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65451 data=0x276755b
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65442 data=0x2767564
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65426 data=0x2767574
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65406 data=0x2767588
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65395 data=0x2767593
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65384 data=0x276759e
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataRecord::DataRecord len=65373 data=0x27675a9
ERROR:   Jun 21 16:52:03 2016 (asterixformat.cxx) DataItem format not defined for CAT001/I
Segmentation fault
`

**Comment by dsalantic** [comment] 2016-06-27 07:31
Are you trying to decode Asterix CAT 240 ?
Note that for CAT240 you need to create XML definition file, because it is not yet supported.
If you are willing to create CAT240 XML, please see definitions of other categories (see in config folder), and I will help you if you experience some problems or have .

Anyway, even if there is no CAT240 definition, application shouldn't crash. I'll investigate.

**Comment by dsalantic** [comment] 2016-06-27 08:16
I implemented a fix to prevent segmenentation fault.
Note that the problem with CAT240 still remains, but it is not a bug, so I'm closing this problem.

**Closed by dsalantic** 2016-06-27 08:16 UTC

**Comment by julianraheema** [comment] 2017-05-16 18:31
Hi @dsalantic I am trying to parse CAT 240 and when I am running on windows 7 

asterix.exe -i 237.192.42.77:10.0.2.14:4277 I am having this error 
ERROR: May 16 11:25:50 2017 (asterixformat.cxx) UAP not found for category 240
ERROR: May 16 11:25:50 2017 (asterixformat.cxx) Record not parsed properly. CAT240 len=1376

Please help how to fix that.
Thank you.

**Comment by dsalantic** [comment] 2017-05-17 07:16
I found some time to implement Category 240.
Please take latest version and try it. Note that I do not have sample of CAT240, so I couldn't test it.

**Comment by julianraheema** [comment] 2017-05-17 15:46
@dsalantic  Thank you so much for your support and implementing the CAT 240. I download the latest tool and the error is fixed. On your xml file at id="030" you have only CHAR bits represented where as on the CAT 240 v1.3 documentation has REP bits from bit "16" to "9" is that makes any difference? 

Again I appreciate your help. Thank you.

**Comment by dsalantic** [comment] 2017-05-18 06:48
This should be OK, because first byte is a repetition factor and it is automatically taken by tag <Repetitive>.
Please try it and let me know if it works as expected, since I can't try it myself. If you can send me some sample data I can make automated test.
Thank you for using asterix decoder.

**Comment by julianraheema** [comment] 2017-05-18 16:11
It seems working and parsing the data, but let me do more testing then I can send you a sample output. Thank you.

**Comment by julianraheema** [comment] 2017-05-19 21:07
It seems working and parsing the data, but let me do more testing then I can send you a sample output. Thank you.
