### ISSUE TITLE
Strange segmentation fault error when parsing a message

### ISSUE THREAD

**Issue by marius190** [CroatiaControlLtd/asterix#196] opened 2022-02-09 23:56 UTC
Hello everyone, 

I was decoding **one by one** ASTERIX messages from an .ast file with Python. The steps followed are the ones suggested by @dsalantic in the previous post, here:

[https://github.com/CroatiaControlLtd/asterix/issues/194](url)

Everything **worked perfectly until** decoding **message 472**. When decoding the message 472 on google collab I got a prompt message saying _"your season has failed for an unknown reason"_.  If I skip decoding of message 472  and I go on with the next one, everything works fine for some hundred messages until again error is repeated for another message. Thinking that this may be because of google collab (server) restrictions, I executed the file on a Linux server we have. When executing the file by python3 file.py in the command line I got the following error:

![Error](https://user-images.githubusercontent.com/47638884/153306838-7971d07e-ba13-4571-bff6-e8e41335f2d9.jpeg)

Is a very strange error that only appears when using asterix.parse(msg). The error is very elusive, namely, Python actually does not return an error. In consequence, the try-except statements does not detect it. I am not an expert, but the error looks more to be related to Linux and memory access. 

----- Obs:
+The msg in which the error appears is of category 21 and has a total length (in bytes) of 73. 
+Print of msg 472 gives:
`b'\x15\x00I\xf7\x1b1\x03\xc3g\x04\x14\xd7\x11A\x00\x0c\xfc\x01\x1c\xc6M\xfdw\x04\x0ec&g\xfe\xbb\x81\xc8L\x01\xe98F\x0b6\xfa\x8d\x01R\n8F(\x0537\xc9h\x03\x08\x01\x05\xe8\x01U\x01\x11@\x02\x18\x02\x19\x18\x05\x08a\x11\x82\x15\x00c\xf7\x1b{k\xd3\xa7\x04\x14\xd7\x01\x01\x00\x0c'`
+I attach the code for reproducibility and the .ast file. 

-----
```
# TEST ASTERIX LIBRARY -- CODE JUST TO PRINT DECODED .ast OUTPUTS
import asterix
import struct # To transform bytes b'\ to binary 

sample_filename = "200223-cen-080001_PAR1_ADSB.ast"

with open(sample_filename, "rb") as f:
  data = f.read() 

  k=1
  pos=0
  while k<473: # ERROR appears when k=472

    CAT=data[pos] 
    LON=data[pos+1:pos+3]

    #CAT=struct.unpack('B',CAT)
    LON=struct.unpack('>H',LON)
    LON = list(LON)[0]
    # print(CAT,LON)
    
    dato=data[pos:pos+LON]
    packed=asterix.parse(dato) # Erros happens in asterix.parse 
    pos=pos+LON
    k += 1
```

**Comment by marius190** [comment] 2022-02-09 23:59
Link to data:
https://drive.google.com/file/d/14Pf4GQSuby2OfRJMF5uPJHacqulLshmP/view?usp=sharing

**Comment by dsalantic** [comment] 2022-02-10 12:01
Thank you for your report and data. I reproduced your problem and obviously there is some memory violation in the parser.
Unfortunately, python version of the parser does not return all error warnings, but when I run your data in executable version of parser (you can build it from source code by running make in src folder), I see some errors in your data that is not parsed correctly.
It can be that your data is not compliant to standard, or there is some error in category definition files.
Anyway, I will try to fix the problem (to not crash at least), but can't promise when. It depends on my free time.

**Comment by karmawangchu** [comment] 2023-10-23 06:56
Hello @dsalantic. Thank you for this wonderful package. I am facing the same segmentation error when using the python parser. Any updates on the fix or any pointers on how we might be able to try fix it. Thank you.

**Comment by dsalantic** [comment] 2023-10-23 08:17
@marius190 @karmawangchu 
I just tried the sample @marius190 sent and I can't reproduce the problem any more. Is it possible that this has been fixed in some of  the previous commits?
@karmawangchu Can you send you application and data sample ?
Also make sure that you use the latest asterix version.

**Comment by dsalantic** [comment] 2023-10-23 09:13
Maybe this was related to problem: https://github.com/CroatiaControlLtd/asterix/issues/202
It should be fixed now.

**Comment by karmawangchu** [comment] 2023-10-24 12:11
Thanks for prompt action. I tried the latest build and also the one in the branch (that's still not merged). With both I am still getting segmentation error. 
I am just trying if the parser works on my data or not so the code is very simple 

`import asterix 

sample_filename = 'sample_filename.ast'   # replace with actual .ast file name
with open(sample_filename, "rb") as f:
    data = f.read()
    parsed = asterix.parse(data)
    print(parsed)
`

I have put two sets of data in the google drive below: one where the parser works without issue and other where it gives segmentation error. The data are from the same system. 

https://drive.google.com/drive/folders/1hJQn7z5W18726pcumhL6J6aY-gCP24Qw?usp=sharing 

Thank you.

**Comment by dsalantic** [comment] 2023-10-25 11:50
Thanks for the sample. I confirm that there is a segmentation error and I'll try to find the problem.

**Comment by dsalantic** [comment] 2023-10-26 06:42
@karmawangchu 
The problem is in your data. It does not contain just Asterix packets, but has 8 bytes of header before each packet.
Unfortunately my parser is not able to recognize the start of the asterix packet (maybe in some future version it will).
So, for now, you need to remove this header and then send each packet to the parser.

Here is the sample application that works with your data:

`
import asterix
import struct

sample_filename = 'install/sample_data/TP1_20230803_080000_Cat21_Cat23_Cat25_Cat247.ast'

with open(sample_filename, "rb") as f:
    data = f.read()
    k = 1
    pos = 8
    while pos<len(data):
        CAT=data[pos] 
        LON=data[pos+1:pos+3]
        LON=struct.unpack('>H',LON)
        LON = list(LON)[0]
        dato=data[pos:pos+LON]
        packed=asterix.parse(dato)
        print('\n', k, '. CAT', CAT, ' LEN=', LON)
        print(packed)
        pos=pos+LON+8
        k += 1
`

**Closed by dsalantic** 2023-10-26 06:42 UTC
